version: "3.9"
services:
#  frontend:
#    build:
#      context: ./frontend
#    container_name: frontend
#    ports:
#      - "80:3000"
#    restart: always
#    environment:
#      NEXT_PUBLIC_API_URI: http://backend:8000
#    networks:
#      - network
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    restart: always
    environment:
      ML_API_URI: "${ML_API_URI}"
      TEST_PHOTO_NAME: test_response.jpg
      DATABASE_URL: postgresql://user:password@db:5432/database
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database

volumes:
  postgres_data:
networks:
  network:
