version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "80:3000"
    restart: always
    networks:
      - network
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    restart: always
    networks:
      - network

networks:
  network:
